# Generated by Django 4.2.9 on 2024-02-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='published',
            field=models.DateField(),
        ),
    ]
