# Generated by Django 4.2.9 on 2024-02-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_alter_painting_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.URLField(default=None, max_length=255),
        ),
    ]
